language: julia
os:
    - osx
    - linux
julia:
    - release
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("KernelEstimator"); Pkg.test("KernelEstimator"; coverage=true)';
after_success:
    - julia -e 'cd(Pkg.dir("KernelEstimator")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
